### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by indolering** [corny/dnscheck#4]
I couldn't find a repo for the website, but there is no HTTPS cert (at least for the raw lists).

**Comment by corny** [comment]
Thanks for the suggestion to add HTTPS. [public-dns.info](https://public-dns.info) is now available via HTTPS. I also added permanent redirects for the pages. The CSV/JSON/TXT downloads are available via HTTP **and** HTTPS.

**Comment by indolering** [comment]
Thank you **sooo** much for this, it makes research (and winning arguments about DNSSEC) so much easier!  You should put up Bitcoin and ZCash addresses for tips!
